version: '2'

services:
  website:
    depends_on:
      - 'nginx-proxy'
      - 'letsencrypt-nginx-proxy-companion'
    build: .
    volumes:
      - '/home/pi/portfolio_site:/app'
    environment:
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_HOST=www.codemang.com
      - LETSENCRYPT_HOST=www.codemang.com
      - LETSENCRYPT_EMAIL=nateboop@gmail.com

  nginx-proxy:
    image: alexanderkrause/rpi-nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: alexanderkrause/rpi-letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs:rw


networks:
  default:
    external:
      name: nginx-proxy
